baseURL: 'https://bubnovd.net/'
languageCode: 'en-us'
title: 'Админская фамилия'
theme: "hugo-theme-cleanwhite"

params:
  header_image: "img/aksai.jpg"
  description: "Make Sysadmins Great Again"
  slogan: "Make Sysadmins Great Again"
  bookmarks: true
  about_me: true
  readingTime: true
  page_view_conter: true

  featured_tags: true 
  featured_condition_size: 1 

  omit_categories: false
  social:
    linkedin: https://www.linkedin.com/in/bubnovd/
    github: https://github.com/bubnovd
  #  email: "wfg"
    telegram: "mikrotikninja"
  #  wechat: "dd"
  #  mastodon: "f"
  #  keybase: "f" 
  #  xing: "f"

  sidebar_about_description: "DevSecOps, Kubernetes, GitLab, Mikrotik Ninja"
  ##sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar: "img/Mikrotik_Ninja_Logo.png"      # use absolute URL, seeing it's used in both `/` and `/about/`
  bookmark_link:
    - title: "Telegram channel"
      href: "https://t.me/mikrotikninja"

  addtional_menus:
    - title: "Archive"
      href: "/archive/"

  giscus:
    data-repo: "bubnovd/bubnovd.github.io"
    data-repo-id: "R_kgDOH3j2Yg"
    data-category: "Announcements"
    data-category-id: "DIC_kwDOH3j2Ys4C65a7"
    data-mapping: "title"
    data-strict: "0"
    data-reactions-enabled: "1"
    data-emit-metadata: "0"
    data-input-position: "bottom"
    data-theme: "light"
    data-lang: "en"
    crossorigin: "anonymous"

services:
  googleAnalytics:
    id: G-TEHWVZ1W9Q
