baseURL: 'https://bubnovd.net/'
languageCode: 'en-us'
title: 'Админская фамилия'
theme: "hugo-theme-cleanwhite"

disqusShortname: bubnovd-github-io

params:
  header_image: "img/aksai.jpg"
  description: "Make Sysadmins Great Again"
  slogan: "Make Sysadmins Great Again"
  bookmarks: true
  about_me: true
  readingTime: true
  page_view_conter: true

  featured_tags: true 
  featured_condition_size: 1 

  omit_categories: false
  social:
    rss: true
    linkedin: https://www.linkedin.com/in/bubnovd/
    github: https://github.com/bubnovd
  #  email: "wfg"
    telegram: "https://t.me/mikrotikninja"
  #  wechat: "dd"
  #  mastodon: "f"
  #  keybase: "f" 
  #  xing: "f"

  sidebar_about_description: "DevSecOps, Kubernetes, GitLab, Mikrotik Ninja"
  ##sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar: "img/Mikrotik_Ninja_Logo.png"      # use absolute URL, seeing it's used in both `/` and `/about/`
  bookmark_link:
    - title: "Telegram channel"
      href: "https://t.me/mikrotikninja"

  addtional_menus:
    - title: "Archive"
      href: "/archive/"

services:
  googleAnalytics:
    id: 111064824 #G-XXXXXXXXX
#markup:
#  tableOfContents:
#    endLevel: 2
#    startLevel: 1
#  highlight:
#    style: "dracula"