baseURL: 'https://bubnovd.net/'
languageCode: 'en-us'
title: 'Админская фамилия'
theme: "hugo-theme-cleanwhite"

disqusShortname: bubnovd-github-io

params:
  header_image: "img/khs22/logo.jpg"
  description: "My blog about IT"
  slogan: "Make Sysadmins Great Again"
  readingTime: true


